import React from 'react'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children?: React.ReactNode,modal?: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-full'> 
          <Navbar/>
          {props.modal}
          {props.children}
        </div>
      </body>
    </html>
  )
}
